INSERT INTO `hotel_service` (`Service`,`Hotel_ID`) VALUES ('Bar',3);
INSERT INTO `hotel_service` (`Service`,`Hotel_ID`) VALUES ('Bar',6);
INSERT INTO `hotel_service` (`Service`,`Hotel_ID`) VALUES ('Bar',9);
INSERT INTO `hotel_service` (`Service`,`Hotel_ID`) VALUES ('Children’s Play Area',4);
INSERT INTO `hotel_service` (`Service`,`Hotel_ID`) VALUES ('Conference Room',2);
INSERT INTO `hotel_service` (`Service`,`Hotel_ID`) VALUES ('Conference Room',5);
INSERT INTO `hotel_service` (`Service`,`Hotel_ID`) VALUES ('Conference Room',9);
INSERT INTO `hotel_service` (`Service`,`Hotel_ID`) VALUES ('Free Breakfast',2);
INSERT INTO `hotel_service` (`Service`,`Hotel_ID`) VALUES ('Free Breakfast',7);
INSERT INTO `hotel_service` (`Service`,`Hotel_ID`) VALUES ('Free WiFi',1);
INSERT INTO `hotel_service` (`Service`,`Hotel_ID`) VALUES ('Free WiFi',4);
INSERT INTO `hotel_service` (`Service`,`Hotel_ID`) VALUES ('Free WiFi',6);
INSERT INTO `hotel_service` (`Service`,`Hotel_ID`) VALUES ('Free WiFi',8);
INSERT INTO `hotel_service` (`Service`,`Hotel_ID`) VALUES ('Free WiFi',9);
INSERT INTO `hotel_service` (`Service`,`Hotel_ID`) VALUES ('Gym',1);
INSERT INTO `hotel_service` (`Service`,`Hotel_ID`) VALUES ('Gym',2);
INSERT INTO `hotel_service` (`Service`,`Hotel_ID`) VALUES ('Gym',5);
INSERT INTO `hotel_service` (`Service`,`Hotel_ID`) VALUES ('Gym',7);
INSERT INTO `hotel_service` (`Service`,`Hotel_ID`) VALUES ('Gym',9);
INSERT INTO `hotel_service` (`Service`,`Hotel_ID`) VALUES ('Gym',10);
INSERT INTO `hotel_service` (`Service`,`Hotel_ID`) VALUES ('Kids Club',7);
INSERT INTO `hotel_service` (`Service`,`Hotel_ID`) VALUES ('Parking',2);
INSERT INTO `hotel_service` (`Service`,`Hotel_ID`) VALUES ('Parking',4);
INSERT INTO `hotel_service` (`Service`,`Hotel_ID`) VALUES ('Parking',6);
INSERT INTO `hotel_service` (`Service`,`Hotel_ID`) VALUES ('Parking',8);
INSERT INTO `hotel_service` (`Service`,`Hotel_ID`) VALUES ('Restaurant',3);
INSERT INTO `hotel_service` (`Service`,`Hotel_ID`) VALUES ('Restaurant',5);
INSERT INTO `hotel_service` (`Service`,`Hotel_ID`) VALUES ('Restaurant',8);
INSERT INTO `hotel_service` (`Service`,`Hotel_ID`) VALUES ('Restaurant',10);
INSERT INTO `hotel_service` (`Service`,`Hotel_ID`) VALUES ('Spa',1);
INSERT INTO `hotel_service` (`Service`,`Hotel_ID`) VALUES ('Spa',5);
INSERT INTO `hotel_service` (`Service`,`Hotel_ID`) VALUES ('Spa',7);
INSERT INTO `hotel_service` (`Service`,`Hotel_ID`) VALUES ('Spa',10);
INSERT INTO `hotel_service` (`Service`,`Hotel_ID`) VALUES ('Swimming Pool',1);
INSERT INTO `hotel_service` (`Service`,`Hotel_ID`) VALUES ('Swimming Pool',3);
INSERT INTO `hotel_service` (`Service`,`Hotel_ID`) VALUES ('Swimming Pool',6);
INSERT INTO `hotel_service` (`Service`,`Hotel_ID`) VALUES ('Swimming Pool',10);
